version: "3.9"

services:
  postgres_database:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: lumi
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d lumi -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres_database

  backend-api:
    build: .
    depends_on:
      postgres_database:
        condition: service_healthy
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres_database:5432/lumi"
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
